[build-system]
build-backend = "cmeel.build"
requires = [
  "cmeel[build]"
]

[project]
description = "Database for solo robot using hpp-rbprm"
license = "BSD-2-Clause"
name = "solo-rbprm"
version = "5.0.0"

[tool.cmeel]
has-binaries = false

[tool.isort]
profile = "black"
